dist: trusty
sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.13.2
  - 2.12.11

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "nb3sAn3Ro0aug+UmH6zxMNMkRaeXcggmtgAshnuAUiBe1qyXId/hq1HsArCty1OYual9Dbc1pUkBjWbQuejBQAOZAPQb8yOmO7JKrnUpAhz5HoWSZ6LPohgg87j5bWz+xRwmcoR3Y1MvqIGpqv6AAD0Xr8n5UPwabI8L7LbYojm+T4Nyklret3Gjd7swH2PhYiCKerZqFI6SeRtMsFuCQgKPae9q8LZOmd1dRa2rG2pseMlfwMlhzyYEQu5OIFrYPVvKo/0mCJlvSrxQ95kd3n1UWeav311YIOc6Q8VhNwV151JhdWUXVp2XFwMSGQ0YjtDK/EffQmbQBeIMJfMWdVVj8R/SQSxw7+3ACREhkNTMMubpmz8lVgSgJmMcAdxEJkk3dKTZIFkxl/C9YXtIm1aX2iUVz5SM/3By9lLuYizT/0XK2tPCbHywaN2lvGMsqwyqAUHvAhdu0YfWFJSNZuXBF8bvXyvzzVqk+hRvPsqvW6kyZsbINZUw47rd+f/C9L8mbaLXaVparOkIwVsK7aGCdd994E47vYTgW2RqPpUJeWZffLbklRYpO2Dl1hNPC/BytGlAJ7xuOkStj4YCbTRjZs4lHTgxe8JajtwYAxLZwQJpQER7yJIQiXnmYbqcA8bacxYlIvJEUp3XFUz7bKkaH94LBVig8SU3VAhw24Y="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete